package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"reflect"

	"github.com/privyy-io/grimlock/go/grimlock"
	"github.com/privyy-io/grimlock/go/grimlock/types"
)

// TestData represents all test data generated by TypeScript
type TestData struct {
	// Key Generation Tests
	KeyPair struct {
		PrivateKey string `json:"privateKey"`
		PublicKey  string `json:"publicKey"`
	} `json:"keyPair"`

	// Key Derivation Tests
	PasscodeDerivation struct {
		Passcode string `json:"passcode"`
		Salt     string `json:"salt"`
		Params   struct {
			TimeCost    uint32 `json:"timeCost"`
			MemoryCost  uint32 `json:"memoryCost"`
			Parallelism uint8  `json:"parallelism"`
		} `json:"params"`
		DerivedKey string `json:"derivedKey"`
	} `json:"passcodeDerivation"`

	RecoveryKeyDerivation struct {
		RecoveryKeyBytes string `json:"recoveryKeyBytes"`
		DerivedKey       string `json:"derivedKey"`
	} `json:"recoveryKeyDerivation"`

	// Private Key Encryption Tests
	PrivateKeyEncryption struct {
		PrivateKey    string `json:"privateKey"`
		EncryptionKey string `json:"encryptionKey"`
		AAD           string `json:"aad"`
		Encrypted     struct {
			IV         string `json:"iv"`
			Tag        string `json:"tag"`
			Ciphertext string `json:"ciphertext"`
		} `json:"encrypted"`
	} `json:"privateKeyEncryption"`

	// Message Encryption Tests
	MessageEncryption struct {
		Payload struct {
			UserMessage       string                 `json:"userMessage"`
			AssistantResponse string                 `json:"assistantResponse"`
			OptionalContext   map[string]interface{} `json:"optionalContext"`
		} `json:"payload"`
		UserKeyPair struct {
			PrivateKey string `json:"privateKey"`
			PublicKey  string `json:"publicKey"`
		} `json:"userKeyPair"`
		Context struct {
			ConversationID string `json:"conversationId"`
			MessageID      string `json:"messageId"`
		} `json:"context"`
		Encrypted struct {
			EphemeralPublicKey string `json:"ephemeralPublicKey"`
			IV                 string `json:"iv"`
			Tag                string `json:"tag"`
			Ciphertext         string `json:"ciphertext"`
		} `json:"encrypted"`
	} `json:"messageEncryption"`

	// ECDH Tests
	ECDHTest struct {
		AlicePrivateKey string `json:"alicePrivateKey"`
		AlicePublicKey  string `json:"alicePublicKey"`
		BobPrivateKey   string `json:"bobPrivateKey"`
		BobPublicKey    string `json:"bobPublicKey"`
		SharedSecret    string `json:"sharedSecret"`
	} `json:"ecdhTest"`

	// Recovery Key Test
	RecoveryKeyTest struct {
		RecoveryKey struct {
			Key      string `json:"key"`
			Mnemonic string `json:"mnemonic"`
		} `json:"recoveryKey"`
		PrivateKey string `json:"privateKey"`
		AAD        string `json:"aad"`
		Encrypted  struct {
			IV         string `json:"iv"`
			Tag        string `json:"tag"`
			Ciphertext string `json:"ciphertext"`
		} `json:"encrypted"`
	} `json:"recoveryKeyTest"`
}

func main() {
	// Read test data generated by TypeScript
	inputPath := "../test-data/ts-generated.json"
	jsonData, err := os.ReadFile(inputPath)
	if err != nil {
		panic(fmt.Sprintf("Failed to read JSON file: %v", err))
	}

	var testData TestData
	err = json.Unmarshal(jsonData, &testData)
	if err != nil {
		panic(fmt.Sprintf("Failed to unmarshal JSON: %v", err))
	}

	g := grimlock.New()
	passed := 0
	failed := 0

	fmt.Println("🔍 Verifying TypeScript-generated test data with Go...")
	fmt.Println()

	// Test 1: Passcode Key Derivation
	fmt.Println("1. Testing passcode key derivation...")
	salt, _ := base64.StdEncoding.DecodeString(testData.PasscodeDerivation.Salt)
	expectedKey, _ := base64.StdEncoding.DecodeString(testData.PasscodeDerivation.DerivedKey)
	kdfParams := types.KdfParams{
		Salt: salt,
		Argon2Params: types.Argon2Params{
			TimeCost:    testData.PasscodeDerivation.Params.TimeCost,
			MemoryCost:  testData.PasscodeDerivation.Params.MemoryCost,
			Parallelism: testData.PasscodeDerivation.Params.Parallelism,
		},
	}
	derivedKey, err := g.DerivePasscodeKey(testData.PasscodeDerivation.Passcode, kdfParams)
	if err != nil {
		fmt.Printf("   ❌ Failed to derive passcode key: %v\n", err)
		failed++
	} else if !bytesEqual(derivedKey, expectedKey) {
		fmt.Printf("   ❌ Derived key mismatch\n")
		fmt.Printf("      Expected: %s\n", base64.StdEncoding.EncodeToString(expectedKey))
		fmt.Printf("      Got:      %s\n", base64.StdEncoding.EncodeToString(derivedKey))
		failed++
	} else {
		fmt.Println("   ✅ Passcode key derivation matches")
		passed++
	}

	// Test 2: Recovery Key Derivation
	fmt.Println("2. Testing recovery key derivation...")
	recoveryKeyBytes, _ := base64.StdEncoding.DecodeString(testData.RecoveryKeyDerivation.RecoveryKeyBytes)
	expectedRecoveryKey, _ := base64.StdEncoding.DecodeString(testData.RecoveryKeyDerivation.DerivedKey)
	derivedRecoveryKey, err := g.DeriveRecoveryKey(recoveryKeyBytes)
	if err != nil {
		fmt.Printf("   ❌ Failed to derive recovery key: %v\n", err)
		failed++
	} else if !bytesEqual(derivedRecoveryKey, expectedRecoveryKey) {
		fmt.Printf("   ❌ Derived recovery key mismatch\n")
		fmt.Printf("      Expected: %s\n", base64.StdEncoding.EncodeToString(expectedRecoveryKey))
		fmt.Printf("      Got:      %s\n", base64.StdEncoding.EncodeToString(derivedRecoveryKey))
		failed++
	} else {
		fmt.Println("   ✅ Recovery key derivation matches")
		passed++
	}

	// Test 3: Private Key Decryption
	fmt.Println("3. Testing private key decryption...")
	expectedPrivateKey, _ := base64.StdEncoding.DecodeString(testData.PrivateKeyEncryption.PrivateKey)
	encryptionKey, _ := base64.StdEncoding.DecodeString(testData.PrivateKeyEncryption.EncryptionKey)
	aad, _ := base64.StdEncoding.DecodeString(testData.PrivateKeyEncryption.AAD)
	iv, _ := base64.StdEncoding.DecodeString(testData.PrivateKeyEncryption.Encrypted.IV)
	tag, _ := base64.StdEncoding.DecodeString(testData.PrivateKeyEncryption.Encrypted.Tag)
	ciphertext, _ := base64.StdEncoding.DecodeString(testData.PrivateKeyEncryption.Encrypted.Ciphertext)
	encrypted := types.NewEncryptedPrivateKeyV1(iv, tag, ciphertext)
	decryptedPrivateKey, err := g.DecryptPrivateKey(&encrypted.EncryptedPrivateKey, encryptionKey, aad)
	if err != nil {
		fmt.Printf("   ❌ Failed to decrypt private key: %v\n", err)
		failed++
	} else if !bytesEqual(decryptedPrivateKey, expectedPrivateKey) {
		fmt.Printf("   ❌ Decrypted private key mismatch\n")
		failed++
	} else {
		fmt.Println("   ✅ Private key decryption matches")
		passed++
	}

	// Test 4: Message Decryption
	fmt.Println("4. Testing message decryption...")
	userPrivateKey, _ := base64.StdEncoding.DecodeString(testData.MessageEncryption.UserKeyPair.PrivateKey)
	ephemeralPublicKey, _ := base64.StdEncoding.DecodeString(testData.MessageEncryption.Encrypted.EphemeralPublicKey)
	msgIV, _ := base64.StdEncoding.DecodeString(testData.MessageEncryption.Encrypted.IV)
	msgTag, _ := base64.StdEncoding.DecodeString(testData.MessageEncryption.Encrypted.Tag)
	msgCiphertext, _ := base64.StdEncoding.DecodeString(testData.MessageEncryption.Encrypted.Ciphertext)
	encryptedMessage := types.NewEncryptedMessageV1(ephemeralPublicKey, msgIV, msgTag, msgCiphertext)
	context := types.MessageContext{
		ConversationID: testData.MessageEncryption.Context.ConversationID,
		MessageID:      testData.MessageEncryption.Context.MessageID,
	}
	decryptedPayload, err := g.DecryptMessage(&encryptedMessage.EncryptedMessage, userPrivateKey, context, nil)
	if err != nil {
		fmt.Printf("   ❌ Failed to decrypt message: %v\n", err)
		failed++
	} else if decryptedPayload.UserMessage != testData.MessageEncryption.Payload.UserMessage ||
		decryptedPayload.AssistantResponse != testData.MessageEncryption.Payload.AssistantResponse {
		fmt.Printf("   ❌ Decrypted message payload mismatch\n")
		fmt.Printf("      Expected UserMessage: %s\n", testData.MessageEncryption.Payload.UserMessage)
		fmt.Printf("      Got UserMessage: %s\n", decryptedPayload.UserMessage)
		failed++
	} else {
		fmt.Println("   ✅ Message decryption matches")
		passed++
	}

	// Test 5: ECDH Shared Secret
	fmt.Println("5. Testing ECDH shared secret...")
	alicePrivateKey, _ := base64.StdEncoding.DecodeString(testData.ECDHTest.AlicePrivateKey)
	bobPublicKey, _ := base64.StdEncoding.DecodeString(testData.ECDHTest.BobPublicKey)
	expectedSharedSecret, _ := base64.StdEncoding.DecodeString(testData.ECDHTest.SharedSecret)
	computedSharedSecret, err := g.ComputeSharedSecret(alicePrivateKey, bobPublicKey)
	if err != nil {
		fmt.Printf("   ❌ Failed to compute shared secret: %v\n", err)
		failed++
	} else if !bytesEqual(computedSharedSecret, expectedSharedSecret) {
		fmt.Printf("   ❌ Shared secret mismatch\n")
		failed++
	} else {
		fmt.Println("   ✅ ECDH shared secret matches")
		passed++
	}

	// Verify Bob can also compute the same shared secret
	bobPrivateKey, _ := base64.StdEncoding.DecodeString(testData.ECDHTest.BobPrivateKey)
	alicePublicKey, _ := base64.StdEncoding.DecodeString(testData.ECDHTest.AlicePublicKey)
	bobComputedSecret, err := g.ComputeSharedSecret(bobPrivateKey, alicePublicKey)
	if err != nil {
		fmt.Printf("   ❌ Failed to compute Bob's shared secret: %v\n", err)
		failed++
	} else if !bytesEqual(bobComputedSecret, expectedSharedSecret) {
		fmt.Printf("   ❌ Bob's shared secret mismatch\n")
		failed++
	} else {
		fmt.Println("   ✅ Bob's ECDH shared secret matches")
		passed++
	}

	// Test 6: Recovery Key Private Key Decryption
	fmt.Println("6. Testing recovery key private key decryption...")
	recoveryKey, _ := base64.StdEncoding.DecodeString(testData.RecoveryKeyTest.RecoveryKey.Key)
	expectedRecoveryPrivateKey, _ := base64.StdEncoding.DecodeString(testData.RecoveryKeyTest.PrivateKey)
	recoveryAAD, _ := base64.StdEncoding.DecodeString(testData.RecoveryKeyTest.AAD)
	recoveryIV, _ := base64.StdEncoding.DecodeString(testData.RecoveryKeyTest.Encrypted.IV)
	recoveryTag, _ := base64.StdEncoding.DecodeString(testData.RecoveryKeyTest.Encrypted.Tag)
	recoveryCiphertext, _ := base64.StdEncoding.DecodeString(testData.RecoveryKeyTest.Encrypted.Ciphertext)
	encryptedWithRecovery := types.NewEncryptedPrivateKeyV1(recoveryIV, recoveryTag, recoveryCiphertext)
	recoveryEncryptionKey, err := g.DeriveRecoveryKey(recoveryKey)
	if err != nil {
		fmt.Printf("   ❌ Failed to derive encryption key from recovery key: %v\n", err)
		failed++
	} else {
		decryptedWithRecovery, err := g.DecryptPrivateKey(&encryptedWithRecovery.EncryptedPrivateKey, recoveryEncryptionKey, recoveryAAD)
		if err != nil {
			fmt.Printf("   ❌ Failed to decrypt with recovery key: %v\n", err)
			failed++
		} else if !bytesEqual(decryptedWithRecovery, expectedRecoveryPrivateKey) {
			fmt.Printf("   ❌ Recovery key decryption mismatch\n")
			failed++
		} else {
			fmt.Println("   ✅ Recovery key decryption matches")
			passed++
		}
	}

	// Summary
	fmt.Println()
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Printf("Results: %d passed, %d failed\n", passed, failed)
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

	if failed > 0 {
		os.Exit(1)
	}
}

func bytesEqual(a, b []byte) bool {
	return reflect.DeepEqual(a, b)
}
