"""Cross-compatibility tests for Grimlock crypto module.

These tests verify that Python can decrypt data encrypted by Go/TypeScript
and that Go/TypeScript can decrypt data encrypted by Python.
"""

import json
import os
from pathlib import Path

import pytest

from grimlock import v1
from grimlock.types.common import MessageContext, MessagePayload
from grimlock.utils.encoding import decode_base64, encode_base64


def get_test_data_path(filename: str) -> Path:
    """Get path to test data file."""
    # Look for test data in cross-compatibility-testing directory
    base_path = Path(__file__).parent.parent.parent.parent
    test_data_path = base_path / "cross-compatibility-testing" / "test-data" / filename
    return test_data_path


class TestGoCompatibility:
    """Tests for compatibility with Go-generated data."""

    def test_decrypt_go_encrypted_private_key(self):
        """Test decrypting private key encrypted by Go."""
        test_data_path = get_test_data_path("go-generated.json")
        if not test_data_path.exists():
            pytest.skip("Go test data not found")

        with open(test_data_path) as f:
            test_data = json.load(f)

        # Get encrypted private key data
        encrypted_data = test_data["privateKeyEncryption"]
        encrypted = {
            "iv": decode_base64(encrypted_data["encrypted"]["iv"]),
            "tag": decode_base64(encrypted_data["encrypted"]["tag"]),
            "ciphertext": decode_base64(encrypted_data["encrypted"]["ciphertext"]),
        }
        encryption_key = decode_base64(encrypted_data["encryptionKey"])
        aad = decode_base64(encrypted_data["aad"])
        expected_private_key = decode_base64(encrypted_data["privateKey"])

        from grimlock.types.common import EncryptedPrivateKey

        encrypted_key = EncryptedPrivateKey(
            iv=encrypted["iv"],
            tag=encrypted["tag"],
            ciphertext=encrypted["ciphertext"],
        )

        # Decrypt using Python
        decrypted = v1.decrypt_private_key(encrypted_key, encryption_key, aad)
        assert decrypted == expected_private_key

    def test_decrypt_go_encrypted_message(self):
        """Test decrypting message encrypted by Go."""
        test_data_path = get_test_data_path("go-generated.json")
        if not test_data_path.exists():
            pytest.skip("Go test data not found")

        with open(test_data_path) as f:
            test_data = json.load(f)

        # Get encrypted message data
        msg_data = test_data["messageEncryption"]
        encrypted = {
            "ephemeralPublicKey": decode_base64(msg_data["encrypted"]["ephemeralPublicKey"]),
            "iv": decode_base64(msg_data["encrypted"]["iv"]),
            "tag": decode_base64(msg_data["encrypted"]["tag"]),
            "ciphertext": decode_base64(msg_data["encrypted"]["ciphertext"]),
        }
        user_private_key = decode_base64(msg_data["userKeyPair"]["privateKey"])
        context = MessageContext(
            conversation_id=msg_data["context"]["conversationId"],
            message_id=msg_data["context"]["messageId"],
        )
        expected_payload = MessagePayload(
            user_message=msg_data["payload"]["userMessage"],
            assistant_response=msg_data["payload"]["assistantResponse"],
            context=msg_data["payload"].get("optionalContext"),
        )

        from grimlock.types.common import EncryptedMessage

        encrypted_msg = EncryptedMessage(
            ephemeral_public_key=encrypted["ephemeralPublicKey"],
            iv=encrypted["iv"],
            tag=encrypted["tag"],
            ciphertext=encrypted["ciphertext"],
        )

        # Decrypt using Python
        decrypted = v1.decrypt_message(encrypted_msg, user_private_key, context)
        assert decrypted.user_message == expected_payload.user_message
        assert decrypted.assistant_response == expected_payload.assistant_response

    def test_ecdh_with_go_keys(self):
        """Test ECDH with keys generated by Go."""
        test_data_path = get_test_data_path("go-generated.json")
        if not test_data_path.exists():
            pytest.skip("Go test data not found")

        with open(test_data_path) as f:
            test_data = json.load(f)

        # Get ECDH test data
        ecdh_data = test_data["ecdhTest"]
        alice_private_key = decode_base64(ecdh_data["alicePrivateKey"])
        bob_public_key = decode_base64(ecdh_data["bobPublicKey"])
        expected_shared_secret = decode_base64(ecdh_data["sharedSecret"])

        # Compute shared secret using Python
        shared_secret = v1.compute_shared_secret(alice_private_key, bob_public_key)
        assert shared_secret == expected_shared_secret


class TestTypeScriptCompatibility:
    """Tests for compatibility with TypeScript-generated data."""

    def test_decrypt_typescript_encrypted_private_key(self):
        """Test decrypting private key encrypted by TypeScript."""
        test_data_path = get_test_data_path("ts-generated.json")
        if not test_data_path.exists():
            pytest.skip("TypeScript test data not found")

        with open(test_data_path) as f:
            test_data = json.load(f)

        # Get encrypted private key data
        encrypted_data = test_data["privateKeyEncryption"]
        encrypted = {
            "iv": decode_base64(encrypted_data["encrypted"]["iv"]),
            "tag": decode_base64(encrypted_data["encrypted"]["tag"]),
            "ciphertext": decode_base64(encrypted_data["encrypted"]["ciphertext"]),
        }
        encryption_key = decode_base64(encrypted_data["encryptionKey"])
        aad = decode_base64(encrypted_data["aad"])
        expected_private_key = decode_base64(encrypted_data["privateKey"])

        from grimlock.types.common import EncryptedPrivateKey

        encrypted_key = EncryptedPrivateKey(
            iv=encrypted["iv"],
            tag=encrypted["tag"],
            ciphertext=encrypted["ciphertext"],
        )

        # Decrypt using Python
        decrypted = v1.decrypt_private_key(encrypted_key, encryption_key, aad)
        assert decrypted == expected_private_key

    def test_decrypt_typescript_encrypted_message(self):
        """Test decrypting message encrypted by TypeScript."""
        test_data_path = get_test_data_path("ts-generated.json")
        if not test_data_path.exists():
            pytest.skip("TypeScript test data not found")

        with open(test_data_path) as f:
            test_data = json.load(f)

        # Get encrypted message data
        msg_data = test_data["messageEncryption"]
        encrypted = {
            "ephemeralPublicKey": decode_base64(msg_data["encrypted"]["ephemeralPublicKey"]),
            "iv": decode_base64(msg_data["encrypted"]["iv"]),
            "tag": decode_base64(msg_data["encrypted"]["tag"]),
            "ciphertext": decode_base64(msg_data["encrypted"]["ciphertext"]),
        }
        user_private_key = decode_base64(msg_data["userKeyPair"]["privateKey"])
        context = MessageContext(
            conversation_id=msg_data["context"]["conversationId"],
            message_id=msg_data["context"]["messageId"],
        )
        expected_payload = MessagePayload(
            user_message=msg_data["payload"]["userMessage"],
            assistant_response=msg_data["payload"]["assistantResponse"],
            context=msg_data["payload"].get("optionalContext"),
        )

        from grimlock.types.common import EncryptedMessage

        encrypted_msg = EncryptedMessage(
            ephemeral_public_key=encrypted["ephemeralPublicKey"],
            iv=encrypted["iv"],
            tag=encrypted["tag"],
            ciphertext=encrypted["ciphertext"],
        )

        # Decrypt using Python
        decrypted = v1.decrypt_message(encrypted_msg, user_private_key, context)
        assert decrypted.user_message == expected_payload.user_message
        assert decrypted.assistant_response == expected_payload.assistant_response
