/**
 * TypeScript Test Data Verifier for Cross-Compatibility Testing
 * 
 * Verifies test data generated by Go grimlock implementation
 * using TypeScript grimlock implementation
 */

import * as fs from 'fs';
import * as path from 'path';
import grimlock from '../../typescript/grimlock';

interface TestData {
  keyPair: {
    privateKey: string;
    publicKey: string;
  };
  passcodeDerivation: {
    passcode: string;
    salt: string;
    params: {
      timeCost: number;
      memoryCost: number;
      parallelism: number;
    };
    derivedKey: string;
  };
  recoveryKeyDerivation: {
    recoveryKeyBytes: string;
    derivedKey: string;
  };
  privateKeyEncryption: {
    privateKey: string;
    encryptionKey: string;
    aad: string;
    encrypted: {
      iv: string;
      tag: string;
      ciphertext: string;
    };
  };
  messageEncryption: {
    payload: {
      userMessage: string;
      assistantResponse: string;
      optionalContext: Record<string, unknown>;
    };
    userKeyPair: {
      privateKey: string;
      publicKey: string;
    };
    context: {
      conversationId: string;
      messageId: string;
    };
    encrypted: {
      ephemeralPublicKey: string;
      iv: string;
      tag: string;
      ciphertext: string;
    };
  };
  ecdhTest: {
    alicePrivateKey: string;
    alicePublicKey: string;
    bobPrivateKey: string;
    bobPublicKey: string;
    sharedSecret: string;
  };
  recoveryKeyTest: {
    recoveryKey: {
      key: string;
      mnemonic: string;
    };
    privateKey: string;
    aad: string;
    encrypted: {
      iv: string;
      tag: string;
      ciphertext: string;
    };
  };
}

// Helper to convert base64 to Uint8Array
function fromBase64(base64: string): Uint8Array {
  return new Uint8Array(Buffer.from(base64, 'base64'));
}

// Helper to convert Uint8Array to base64
function toBase64(data: Uint8Array): string {
  return Buffer.from(data).toString('base64');
}

// Helper to compare byte arrays
function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

async function verifyTestData(): Promise<void> {
  console.log('🔍 Verifying Go-generated test data with TypeScript...');
  console.log();

  // Read test data generated by Go
  const inputPath = path.join(__dirname, '../test-data/go-generated.json');
  const jsonData = fs.readFileSync(inputPath, 'utf-8');
  const testData: TestData = JSON.parse(jsonData);

  let passed = 0;
  let failed = 0;

  // Test 1: Passcode Key Derivation
  try {
    console.log('1. Testing passcode key derivation...');
    const salt = fromBase64(testData.passcodeDerivation.salt);
    const expectedKey = fromBase64(testData.passcodeDerivation.derivedKey);
    const kdfParams = {
      salt,
      argon2Params: {
        timeCost: testData.passcodeDerivation.params.timeCost,
        memoryCost: testData.passcodeDerivation.params.memoryCost,
        parallelism: testData.passcodeDerivation.params.parallelism,
      },
    };
    const derivedKey = await grimlock.derivePasscodeKey(
      testData.passcodeDerivation.passcode,
      kdfParams
    );

    if (bytesEqual(derivedKey, expectedKey)) {
      console.log('   ✅ Passcode key derivation matches');
      passed++;
    } else {
      console.log('   ❌ Derived key mismatch');
      console.log(`      Expected: ${toBase64(expectedKey)}`);
      console.log(`      Got:      ${toBase64(derivedKey)}`);
      failed++;
    }
  } catch (error) {
    console.log(`   ❌ Failed to derive passcode key: ${error}`);
    failed++;
  }

  // Test 2: Recovery Key Derivation
  try {
    console.log('2. Testing recovery key derivation...');
    const recoveryKeyBytes = fromBase64(testData.recoveryKeyDerivation.recoveryKeyBytes);
    const expectedRecoveryKey = fromBase64(testData.recoveryKeyDerivation.derivedKey);
    const derivedRecoveryKey = await grimlock.deriveRecoveryKey(recoveryKeyBytes);

    if (bytesEqual(derivedRecoveryKey, expectedRecoveryKey)) {
      console.log('   ✅ Recovery key derivation matches');
      passed++;
    } else {
      console.log('   ❌ Derived recovery key mismatch');
      failed++;
    }
  } catch (error) {
    console.log(`   ❌ Failed to derive recovery key: ${error}`);
    failed++;
  }

  // Test 3: Private Key Decryption
  try {
    console.log('3. Testing private key decryption...');
    const expectedPrivateKey = fromBase64(testData.privateKeyEncryption.privateKey);
    const encryptionKey = fromBase64(testData.privateKeyEncryption.encryptionKey);
    const aad = fromBase64(testData.privateKeyEncryption.aad);
    const encrypted = {
      iv: fromBase64(testData.privateKeyEncryption.encrypted.iv),
      tag: fromBase64(testData.privateKeyEncryption.encrypted.tag),
      ciphertext: fromBase64(testData.privateKeyEncryption.encrypted.ciphertext),
    };

    const decryptedPrivateKey = await grimlock.decryptPrivateKey(
      encrypted,
      encryptionKey,
      aad
    );

    if (bytesEqual(decryptedPrivateKey, expectedPrivateKey)) {
      console.log('   ✅ Private key decryption matches');
      passed++;
    } else {
      console.log('   ❌ Decrypted private key mismatch');
      failed++;
    }
  } catch (error) {
    console.log(`   ❌ Failed to decrypt private key: ${error}`);
    failed++;
  }

  // Test 4: Message Decryption
  try {
    console.log('4. Testing message decryption...');
    const userPrivateKey = fromBase64(testData.messageEncryption.userKeyPair.privateKey);
    const encrypted = {
      ephemeralPublicKey: fromBase64(testData.messageEncryption.encrypted.ephemeralPublicKey),
      iv: fromBase64(testData.messageEncryption.encrypted.iv),
      tag: fromBase64(testData.messageEncryption.encrypted.tag),
      ciphertext: fromBase64(testData.messageEncryption.encrypted.ciphertext),
    };
    const context = {
      conversationId: testData.messageEncryption.context.conversationId,
      messageId: testData.messageEncryption.context.messageId,
    };

    const decryptedPayload = await grimlock.decryptMessage(
      encrypted,
      userPrivateKey,
      context
    );

    if (
      decryptedPayload.userMessage === testData.messageEncryption.payload.userMessage &&
      decryptedPayload.assistantResponse === testData.messageEncryption.payload.assistantResponse
    ) {
      console.log('   ✅ Message decryption matches');
      passed++;
    } else {
      console.log('   ❌ Decrypted message payload mismatch');
      console.log(`      Expected UserMessage: ${testData.messageEncryption.payload.userMessage}`);
      console.log(`      Got UserMessage: ${decryptedPayload.userMessage}`);
      failed++;
    }
  } catch (error) {
    console.log(`   ❌ Failed to decrypt message: ${error}`);
    failed++;
  }

  // Test 5: ECDH Shared Secret
  try {
    console.log('5. Testing ECDH shared secret...');
    const alicePrivateKey = fromBase64(testData.ecdhTest.alicePrivateKey);
    const bobPublicKey = fromBase64(testData.ecdhTest.bobPublicKey);
    const expectedSharedSecret = fromBase64(testData.ecdhTest.sharedSecret);

    // Import ECDH function
    const { computeSharedSecret } = await import('../../typescript/grimlock/versions/v1/ecdh');
    const computedSharedSecret = await computeSharedSecret(alicePrivateKey, bobPublicKey);

    if (bytesEqual(computedSharedSecret, expectedSharedSecret)) {
      console.log('   ✅ ECDH shared secret matches');
      passed++;
    } else {
      console.log('   ❌ Shared secret mismatch');
      failed++;
    }

    // Verify Bob can also compute the same shared secret
    const bobPrivateKey = fromBase64(testData.ecdhTest.bobPrivateKey);
    const alicePublicKey = fromBase64(testData.ecdhTest.alicePublicKey);
    const bobComputedSecret = await computeSharedSecret(bobPrivateKey, alicePublicKey);

    if (bytesEqual(bobComputedSecret, expectedSharedSecret)) {
      console.log('   ✅ Bob\'s ECDH shared secret matches');
      passed++;
    } else {
      console.log('   ❌ Bob\'s shared secret mismatch');
      failed++;
    }
  } catch (error) {
    console.log(`   ❌ Failed to compute shared secret: ${error}`);
    failed += 2;
  }

  // Test 6: Recovery Key Private Key Decryption
  try {
    console.log('6. Testing recovery key private key decryption...');
    const recoveryKey = fromBase64(testData.recoveryKeyTest.recoveryKey.key);
    const expectedRecoveryPrivateKey = fromBase64(testData.recoveryKeyTest.privateKey);
    const recoveryAAD = fromBase64(testData.recoveryKeyTest.aad);
    const encryptedWithRecovery = {
      iv: fromBase64(testData.recoveryKeyTest.encrypted.iv),
      tag: fromBase64(testData.recoveryKeyTest.encrypted.tag),
      ciphertext: fromBase64(testData.recoveryKeyTest.encrypted.ciphertext),
    };

    const recoveryEncryptionKey = await grimlock.deriveRecoveryKey(recoveryKey);
    const decryptedWithRecovery = await grimlock.decryptPrivateKey(
      encryptedWithRecovery,
      recoveryEncryptionKey,
      recoveryAAD
    );

    if (bytesEqual(decryptedWithRecovery, expectedRecoveryPrivateKey)) {
      console.log('   ✅ Recovery key decryption matches');
      passed++;
    } else {
      console.log('   ❌ Recovery key decryption mismatch');
      failed++;
    }
  } catch (error) {
    console.log(`   ❌ Failed to decrypt with recovery key: ${error}`);
    failed++;
  }

  // Summary
  console.log();
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`Results: ${passed} passed, ${failed} failed`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

  if (failed > 0) {
    process.exit(1);
  }
}

// Run the verifier
verifyTestData().catch((error) => {
  console.error('❌ Failed to verify test data:', error);
  process.exit(1);
});
