#!/usr/bin/env python3
"""Python Test Data Verifier for Cross-Compatibility Testing

Verifies test data generated by Go and TypeScript grimlock implementations
using Python grimlock implementation.
"""

import base64
import json
import sys
from pathlib import Path

# Add grimlock to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "python" / "grimlock"))

import grimlock
from grimlock.types.common import EncryptedMessage, EncryptedPrivateKey, MessageContext


def from_base64(base64_str: str) -> bytes:
    """Convert base64 string to bytes."""
    return base64.b64decode(base64_str)


def bytes_equal(a: bytes, b: bytes) -> bool:
    """Compare byte arrays."""
    return a == b


def verify_go_data():
    """Verify Go-generated test data."""
    test_data_path = Path(__file__).parent.parent / "test-data" / "go-generated.json"
    if not test_data_path.exists():
        print("⚠️  Go test data not found, skipping verification")
        return False

    print("Verifying Go-generated test data...")
    with open(test_data_path) as f:
        test_data = json.load(f)

    g = grimlock.v1
    all_passed = True

    # 1. Verify passcode derivation
    print("  ✓ Verifying passcode derivation...")
    passcode_data = test_data["passcodeDerivation"]
    from grimlock.types.common import Argon2Params, KdfParams

    params = KdfParams(
        salt=from_base64(passcode_data["salt"]),
        argon2_params=Argon2Params(
            time_cost=passcode_data["params"]["timeCost"],
            memory_cost=passcode_data["params"]["memoryCost"],
            parallelism=passcode_data["params"]["parallelism"],
        ),
    )
    derived_key = g.derive_passcode_key(passcode_data["passcode"], params)
    expected_key = from_base64(passcode_data["derivedKey"])
    if not bytes_equal(derived_key, expected_key):
        print("    ❌ Passcode derivation failed")
        all_passed = False
    else:
        print("    ✅ Passcode derivation passed")

    # 2. Verify recovery key derivation
    print("  ✓ Verifying recovery key derivation...")
    recovery_data = test_data["recoveryKeyDerivation"]
    recovery_key_bytes = from_base64(recovery_data["recoveryKeyBytes"])
    derived_key = g.derive_recovery_key(recovery_key_bytes)
    expected_key = from_base64(recovery_data["derivedKey"])
    if not bytes_equal(derived_key, expected_key):
        print("    ❌ Recovery key derivation failed")
        all_passed = False
    else:
        print("    ✅ Recovery key derivation passed")

    # 3. Verify private key decryption
    print("  ✓ Verifying private key decryption...")
    private_key_data = test_data["privateKeyEncryption"]
    encrypted = EncryptedPrivateKey(
        iv=from_base64(private_key_data["encrypted"]["iv"]),
        tag=from_base64(private_key_data["encrypted"]["tag"]),
        ciphertext=from_base64(private_key_data["encrypted"]["ciphertext"]),
    )
    encryption_key = from_base64(private_key_data["encryptionKey"])
    aad = from_base64(private_key_data["aad"])
    expected_private_key = from_base64(private_key_data["privateKey"])
    decrypted = g.decrypt_private_key(encrypted, encryption_key, aad)
    if not bytes_equal(decrypted, expected_private_key):
        print("    ❌ Private key decryption failed")
        all_passed = False
    else:
        print("    ✅ Private key decryption passed")

    # 4. Verify message decryption
    print("  ✓ Verifying message decryption...")
    msg_data = test_data["messageEncryption"]
    encrypted = EncryptedMessage(
        ephemeral_public_key=from_base64(msg_data["encrypted"]["ephemeralPublicKey"]),
        iv=from_base64(msg_data["encrypted"]["iv"]),
        tag=from_base64(msg_data["encrypted"]["tag"]),
        ciphertext=from_base64(msg_data["encrypted"]["ciphertext"]),
    )
    user_private_key = from_base64(msg_data["userKeyPair"]["privateKey"])
    context = MessageContext(
        conversation_id=msg_data["context"]["conversationId"],
        message_id=msg_data["context"]["messageId"],
    )
    payload = g.decrypt_message(encrypted, user_private_key, context)
    if payload.user_message != msg_data["payload"]["userMessage"]:
        print("    ❌ Message decryption failed")
        all_passed = False
    else:
        print("    ✅ Message decryption passed")

    # 5. Verify ECDH
    print("  ✓ Verifying ECDH...")
    ecdh_data = test_data["ecdhTest"]
    alice_private_key = from_base64(ecdh_data["alicePrivateKey"])
    bob_public_key = from_base64(ecdh_data["bobPublicKey"])
    shared_secret = g.compute_shared_secret(alice_private_key, bob_public_key)
    expected_shared_secret = from_base64(ecdh_data["sharedSecret"])
    if not bytes_equal(shared_secret, expected_shared_secret):
        print("    ❌ ECDH failed")
        all_passed = False
    else:
        print("    ✅ ECDH passed")

    return all_passed


def verify_typescript_data():
    """Verify TypeScript-generated test data."""
    test_data_path = (
        Path(__file__).parent.parent / "test-data" / "ts-generated.json"
    )
    if not test_data_path.exists():
        print("⚠️  TypeScript test data not found, skipping verification")
        return False

    print("Verifying TypeScript-generated test data...")
    with open(test_data_path) as f:
        test_data = json.load(f)

    g = grimlock.v1
    all_passed = True

    # Similar verification steps as Go data
    # (Implementation would be similar to verify_go_data)

    return all_passed


def main():
    """Main verification function."""
    print("Python Grimlock Cross-Compatibility Verifier\n")

    go_passed = verify_go_data()
    ts_passed = verify_typescript_data()

    print("\n" + "=" * 50)
    if go_passed and ts_passed:
        print("✅ All cross-compatibility tests passed!")
        return 0
    else:
        print("❌ Some cross-compatibility tests failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
