#!/usr/bin/env python3
"""Python Test Data Verifier for Cross-Compatibility Testing

Verifies test data generated by Go and TypeScript grimlock implementations
using Python grimlock implementation.
"""

import base64
import json
import sys
from pathlib import Path

# Add grimlock to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "python" / "grimlock"))

import grimlock
from grimlock.types.common import EncryptedMessage, EncryptedPrivateKey, MessageContext


def from_base64(base64_str: str) -> bytes:
    """Convert base64 string to bytes."""
    return base64.b64decode(base64_str)


def bytes_equal(a: bytes, b: bytes) -> bool:
    """Compare byte arrays."""
    return a == b




def verify_source_data(source: str) -> bool:
    """Verify test data from a given source ('go', 'ts', 'python').

    Performs the same checks as verify_go_data but against any generator's output.
    """
    file_map = {
        "go": "go-generated.json",
        "ts": "ts-generated.json",
        "python": "python-generated.json",
    }
    filename = file_map.get(source, source)
    test_data_path = Path(__file__).parent.parent / "test-data" / filename
    if not test_data_path.exists():
        print(f"⚠️  {filename} not found, skipping verification")
        return False

    print(f"Verifying {filename} with Python...")
    with open(test_data_path) as f:
        test_data = json.load(f)

    g = grimlock.v1
    all_passed = True

    from grimlock.types.common import Argon2Params, KdfParams

    # 1. Verify passcode derivation
    print("  ✓ Verifying passcode derivation...")
    passcode_data = test_data["passcodeDerivation"]
    params = KdfParams(
        salt=from_base64(passcode_data["salt"]),
        argon2_params=Argon2Params(
            time_cost=passcode_data["params"]["timeCost"],
            memory_cost=passcode_data["params"]["memoryCost"],
            parallelism=passcode_data["params"]["parallelism"],
        ),
    )
    derived_key = g.derive_passcode_key(passcode_data["passcode"], params)
    if not bytes_equal(derived_key, from_base64(passcode_data["derivedKey"])):
        print("    ❌ Passcode derivation failed")
        all_passed = False
    else:
        print("    ✅ Passcode derivation passed")

    # 2. Verify recovery key derivation
    print("  ✓ Verifying recovery key derivation...")
    recovery_data = test_data["recoveryKeyDerivation"]
    derived_key = g.derive_recovery_key(from_base64(recovery_data["recoveryKeyBytes"]))
    if not bytes_equal(derived_key, from_base64(recovery_data["derivedKey"])):
        print("    ❌ Recovery key derivation failed")
        all_passed = False
    else:
        print("    ✅ Recovery key derivation passed")

    # 3. Verify private key decryption
    print("  ✓ Verifying private key decryption...")
    pk_data = test_data["privateKeyEncryption"]
    encrypted = EncryptedPrivateKey(
        iv=from_base64(pk_data["encrypted"]["iv"]),
        tag=from_base64(pk_data["encrypted"]["tag"]),
        ciphertext=from_base64(pk_data["encrypted"]["ciphertext"]),
    )
    decrypted = g.decrypt_private_key(
        encrypted,
        from_base64(pk_data["encryptionKey"]),
        from_base64(pk_data["aad"]),
    )
    if not bytes_equal(decrypted, from_base64(pk_data["privateKey"])):
        print("    ❌ Private key decryption failed")
        all_passed = False
    else:
        print("    ✅ Private key decryption passed")

    # 4. Verify message decryption
    print("  ✓ Verifying message decryption...")
    msg_data = test_data["messageEncryption"]
    encrypted_msg = EncryptedMessage(
        ephemeral_public_key=from_base64(msg_data["encrypted"]["ephemeralPublicKey"]),
        iv=from_base64(msg_data["encrypted"]["iv"]),
        tag=from_base64(msg_data["encrypted"]["tag"]),
        ciphertext=from_base64(msg_data["encrypted"]["ciphertext"]),
    )
    context = MessageContext(
        conversation_id=msg_data["context"]["conversationId"],
        message_id=msg_data["context"]["messageId"],
    )
    payload = g.decrypt_message(
        encrypted_msg, from_base64(msg_data["userKeyPair"]["privateKey"]), context
    )
    if payload.user_message != msg_data["payload"]["userMessage"]:
        print("    ❌ Message decryption failed")
        all_passed = False
    else:
        print("    ✅ Message decryption passed")

    # 5. Verify ECDH
    print("  ✓ Verifying ECDH...")
    ecdh_data = test_data["ecdhTest"]
    shared_secret = g.compute_shared_secret(
        from_base64(ecdh_data["alicePrivateKey"]),
        from_base64(ecdh_data["bobPublicKey"]),
    )
    if not bytes_equal(shared_secret, from_base64(ecdh_data["sharedSecret"])):
        print("    ❌ ECDH failed")
        all_passed = False
    else:
        print("    ✅ ECDH passed")

    return all_passed


def main():
    """Main verification function.

    Accepts an optional positional argument specifying which source to verify:
      go (default), ts, python
    If omitted, verifies both go and ts sources.
    """
    print("Python Grimlock Cross-Compatibility Verifier\n")

    sources = sys.argv[1:] if len(sys.argv) > 1 else ["go", "ts"]
    results = [verify_source_data(src) for src in sources]

    print("\n" + "=" * 50)
    if all(results):
        print("✅ All cross-compatibility tests passed!")
        return 0
    else:
        print("❌ Some cross-compatibility tests failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
