package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"

	"github.com/privyy/grimlock"
	"github.com/privyy/grimlock/types"
	"github.com/privyy/grimlock/utils"
)

// TestData represents all test data generated by Go
type TestData struct {
	// Key Generation Tests
	KeyPair struct {
		PrivateKey string `json:"privateKey"`
		PublicKey  string `json:"publicKey"`
	} `json:"keyPair"`

	// Key Derivation Tests
	PasscodeDerivation struct {
		Passcode string `json:"passcode"`
		Salt     string `json:"salt"`
		Params   struct {
			TimeCost    uint32 `json:"timeCost"`
			MemoryCost  uint32 `json:"memoryCost"`
			Parallelism uint8  `json:"parallelism"`
		} `json:"params"`
		DerivedKey string `json:"derivedKey"`
	} `json:"passcodeDerivation"`

	RecoveryKeyDerivation struct {
		RecoveryKeyBytes string `json:"recoveryKeyBytes"`
		DerivedKey       string `json:"derivedKey"`
	} `json:"recoveryKeyDerivation"`

	// Private Key Encryption Tests
	PrivateKeyEncryption struct {
		PrivateKey    string `json:"privateKey"`
		EncryptionKey string `json:"encryptionKey"`
		AAD           string `json:"aad"`
		Encrypted     struct {
			IV         string `json:"iv"`
			Tag        string `json:"tag"`
			Ciphertext string `json:"ciphertext"`
		} `json:"encrypted"`
	} `json:"privateKeyEncryption"`

	// Message Encryption Tests
	MessageEncryption struct {
		Payload struct {
			UserMessage       string                 `json:"userMessage"`
			AssistantResponse string                 `json:"assistantResponse"`
			OptionalContext   map[string]interface{} `json:"optionalContext"`
		} `json:"payload"`
		UserKeyPair struct {
			PrivateKey string `json:"privateKey"`
			PublicKey  string `json:"publicKey"`
		} `json:"userKeyPair"`
		Context struct {
			ConversationID string `json:"conversationId"`
			MessageID      string `json:"messageId"`
		} `json:"context"`
		Encrypted struct {
			EphemeralPublicKey string `json:"ephemeralPublicKey"`
			IV                 string `json:"iv"`
			Tag                string `json:"tag"`
			Ciphertext         string `json:"ciphertext"`
		} `json:"encrypted"`
	} `json:"messageEncryption"`

	// ECDH Tests
	ECDHTest struct {
		AlicePrivateKey string `json:"alicePrivateKey"`
		AlicePublicKey  string `json:"alicePublicKey"`
		BobPrivateKey   string `json:"bobPrivateKey"`
		BobPublicKey    string `json:"bobPublicKey"`
		SharedSecret    string `json:"sharedSecret"`
	} `json:"ecdhTest"`

	// Recovery Key Test
	RecoveryKeyTest struct {
		RecoveryKey struct {
			Key      string `json:"key"`
			Mnemonic string `json:"mnemonic"`
		} `json:"recoveryKey"`
		PrivateKey string `json:"privateKey"`
		AAD        string `json:"aad"`
		Encrypted  struct {
			IV         string `json:"iv"`
			Tag        string `json:"tag"`
			Ciphertext string `json:"ciphertext"`
		} `json:"encrypted"`
	} `json:"recoveryKeyTest"`
}

func main() {
	testData := TestData{}
	g := grimlock.New()

	// 1. Key Generation Test
	fmt.Println("Generating key pair...")
	keyPair, err := g.GenerateKeyPair()
	if err != nil {
		panic(fmt.Sprintf("Failed to generate key pair: %v", err))
	}
	testData.KeyPair.PrivateKey = base64.StdEncoding.EncodeToString(keyPair.PrivateKey)
	testData.KeyPair.PublicKey = base64.StdEncoding.EncodeToString(keyPair.PublicKey)

	// 2. Passcode Key Derivation Test
	fmt.Println("Deriving passcode key...")
	passcode := "MySecurePasscode123!"
	salt, err := g.GenerateSalt()
	if err != nil {
		panic(fmt.Sprintf("Failed to generate salt: %v", err))
	}
	kdfParams := types.KdfParams{
		Salt: salt,
		Argon2Params: types.Argon2Params{
			TimeCost:    4,
			MemoryCost:  128 * 1024, // 128MB
			Parallelism: 2,
		},
	}
	derivedKey, err := g.DerivePasscodeKey(passcode, kdfParams)
	if err != nil {
		panic(fmt.Sprintf("Failed to derive passcode key: %v", err))
	}
	testData.PasscodeDerivation.Passcode = passcode
	testData.PasscodeDerivation.Salt = base64.StdEncoding.EncodeToString(salt)
	testData.PasscodeDerivation.Params.TimeCost = kdfParams.Argon2Params.TimeCost
	testData.PasscodeDerivation.Params.MemoryCost = kdfParams.Argon2Params.MemoryCost
	testData.PasscodeDerivation.Params.Parallelism = kdfParams.Argon2Params.Parallelism
	testData.PasscodeDerivation.DerivedKey = base64.StdEncoding.EncodeToString(derivedKey)

	// 3. Recovery Key Derivation Test
	fmt.Println("Deriving recovery key...")
	recoveryKey, err := g.GenerateRecoveryKey()
	if err != nil {
		panic(fmt.Sprintf("Failed to generate recovery key: %v", err))
	}
	recoveryDerivedKey, err := g.DeriveRecoveryKey(recoveryKey.Key)
	if err != nil {
		panic(fmt.Sprintf("Failed to derive recovery key: %v", err))
	}
	testData.RecoveryKeyDerivation.RecoveryKeyBytes = base64.StdEncoding.EncodeToString(recoveryKey.Key)
	testData.RecoveryKeyDerivation.DerivedKey = base64.StdEncoding.EncodeToString(recoveryDerivedKey)

	// 4. Private Key Encryption Test
	fmt.Println("Encrypting private key...")
	privateKeyToEncrypt := keyPair.PrivateKey
	encryptionKey := derivedKey // Use the derived key from passcode
	aad := []byte("user@example.com")
	encryptedPrivateKey, err := g.EncryptPrivateKey(privateKeyToEncrypt, encryptionKey, aad)
	if err != nil {
		panic(fmt.Sprintf("Failed to encrypt private key: %v", err))
	}
	testData.PrivateKeyEncryption.PrivateKey = base64.StdEncoding.EncodeToString(privateKeyToEncrypt)
	testData.PrivateKeyEncryption.EncryptionKey = base64.StdEncoding.EncodeToString(encryptionKey)
	testData.PrivateKeyEncryption.AAD = base64.StdEncoding.EncodeToString(aad)
	testData.PrivateKeyEncryption.Encrypted.IV = base64.StdEncoding.EncodeToString(encryptedPrivateKey.IV)
	testData.PrivateKeyEncryption.Encrypted.Tag = base64.StdEncoding.EncodeToString(encryptedPrivateKey.Tag)
	testData.PrivateKeyEncryption.Encrypted.Ciphertext = base64.StdEncoding.EncodeToString(encryptedPrivateKey.Ciphertext)

	// 5. Message Encryption Test
	fmt.Println("Encrypting message...")
	userKeyPair, err := g.GenerateKeyPair()
	if err != nil {
		panic(fmt.Sprintf("Failed to generate user key pair: %v", err))
	}
	payload := types.MessagePayload{
		UserMessage:       "Hello, this is a test message!",
		AssistantResponse: "I understand. This is a response.",
		OptionalContext: map[string]interface{}{
			"timestamp": "2024-01-15T10:30:00Z",
			"metadata":  "test",
		},
	}
	context := types.MessageContext{
		ConversationID: "conv-123",
		MessageID:      "msg-456",
	}
	encryptedMessage, err := g.EncryptMessage(payload, userKeyPair.PublicKey, context)
	if err != nil {
		panic(fmt.Sprintf("Failed to encrypt message: %v", err))
	}
	testData.MessageEncryption.Payload.UserMessage = payload.UserMessage
	testData.MessageEncryption.Payload.AssistantResponse = payload.AssistantResponse
	testData.MessageEncryption.Payload.OptionalContext = payload.OptionalContext
	testData.MessageEncryption.UserKeyPair.PrivateKey = base64.StdEncoding.EncodeToString(userKeyPair.PrivateKey)
	testData.MessageEncryption.UserKeyPair.PublicKey = base64.StdEncoding.EncodeToString(userKeyPair.PublicKey)
	testData.MessageEncryption.Context.ConversationID = context.ConversationID
	testData.MessageEncryption.Context.MessageID = context.MessageID
	testData.MessageEncryption.Encrypted.EphemeralPublicKey = base64.StdEncoding.EncodeToString(encryptedMessage.EphemeralPublicKey)
	testData.MessageEncryption.Encrypted.IV = base64.StdEncoding.EncodeToString(encryptedMessage.IV)
	testData.MessageEncryption.Encrypted.Tag = base64.StdEncoding.EncodeToString(encryptedMessage.Tag)
	testData.MessageEncryption.Encrypted.Ciphertext = base64.StdEncoding.EncodeToString(encryptedMessage.Ciphertext)

	// 6. ECDH Test
	fmt.Println("Computing shared secret...")
	aliceKeyPair, err := g.GenerateKeyPair()
	if err != nil {
		panic(fmt.Sprintf("Failed to generate Alice's key pair: %v", err))
	}
	bobKeyPair, err := g.GenerateKeyPair()
	if err != nil {
		panic(fmt.Sprintf("Failed to generate Bob's key pair: %v", err))
	}
	sharedSecret, err := g.ComputeSharedSecret(aliceKeyPair.PrivateKey, bobKeyPair.PublicKey)
	if err != nil {
		panic(fmt.Sprintf("Failed to compute shared secret: %v", err))
	}
	testData.ECDHTest.AlicePrivateKey = base64.StdEncoding.EncodeToString(aliceKeyPair.PrivateKey)
	testData.ECDHTest.AlicePublicKey = base64.StdEncoding.EncodeToString(aliceKeyPair.PublicKey)
	testData.ECDHTest.BobPrivateKey = base64.StdEncoding.EncodeToString(bobKeyPair.PrivateKey)
	testData.ECDHTest.BobPublicKey = base64.StdEncoding.EncodeToString(bobKeyPair.PublicKey)
	testData.ECDHTest.SharedSecret = base64.StdEncoding.EncodeToString(sharedSecret)

	// 7. Recovery Key Test
	fmt.Println("Testing recovery key encryption...")
	testRecoveryKey, err := g.GenerateRecoveryKey()
	if err != nil {
		panic(fmt.Sprintf("Failed to generate recovery key: %v", err))
	}
	privateKeyForRecovery := keyPair.PrivateKey
	aadForRecovery := []byte("recovery@example.com")
	recoveryEncryptionKey, err := g.DeriveRecoveryKey(testRecoveryKey.Key)
	if err != nil {
		panic(fmt.Sprintf("Failed to derive encryption key from recovery key: %v", err))
	}
	encryptedWithRecovery, err := g.EncryptPrivateKey(privateKeyForRecovery, recoveryEncryptionKey, aadForRecovery)
	if err != nil {
		panic(fmt.Sprintf("Failed to encrypt with recovery key: %v", err))
	}
	testData.RecoveryKeyTest.RecoveryKey.Key = base64.StdEncoding.EncodeToString(testRecoveryKey.Key)
	testData.RecoveryKeyTest.RecoveryKey.Mnemonic = testRecoveryKey.Mnemonic
	testData.RecoveryKeyTest.PrivateKey = base64.StdEncoding.EncodeToString(privateKeyForRecovery)
	testData.RecoveryKeyTest.AAD = base64.StdEncoding.EncodeToString(aadForRecovery)
	testData.RecoveryKeyTest.Encrypted.IV = base64.StdEncoding.EncodeToString(encryptedWithRecovery.IV)
	testData.RecoveryKeyTest.Encrypted.Tag = base64.StdEncoding.EncodeToString(encryptedWithRecovery.Tag)
	testData.RecoveryKeyTest.Encrypted.Ciphertext = base64.StdEncoding.EncodeToString(encryptedWithRecovery.Ciphertext)

	// Clean up sensitive data
	utils.SecureEraseMultiple(
		keyPair.PrivateKey,
		derivedKey,
		recoveryDerivedKey,
		encryptionKey,
		privateKeyToEncrypt,
		userKeyPair.PrivateKey,
		aliceKeyPair.PrivateKey,
		bobKeyPair.PrivateKey,
		sharedSecret,
		recoveryEncryptionKey,
	)

	// Write to JSON file
	jsonData, err := json.MarshalIndent(testData, "", "  ")
	if err != nil {
		panic(fmt.Sprintf("Failed to marshal JSON: %v", err))
	}

	outputPath := "../test-data/go-generated.json"
	err = os.WriteFile(outputPath, jsonData, 0644)
	if err != nil {
		panic(fmt.Sprintf("Failed to write JSON file: %v", err))
	}

	fmt.Printf("✅ Test data generated successfully: %s\n", outputPath)
}
